name 'qemu_guest'
maintainer 'Dan Clough'
maintainer_email 'dan@clough.xyz'
license 'Apache 2.0'
description 'Installs the QEMU guest agent and guest tools on Linux and Windows virtual machines.'
version '0.2.2'
chef_version '>= 14.0'
issues_url 'https://github.com/danclough/chef-qemu_guest/issues'
source_url 'https://github.com/danclough/chef-qemu_guest'
